language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=4.3.x
    - python: 2.7
      env: PLONE_VERSION=5.0.x
    - python: 2.7
      env: PLONE_VERSION=5.1.x
    - python: 2.7
      env: PLONE_VERSION=5.2.x
    - python: 3.6
      env: PLONE_VERSION=5.2.x
    - python: 3.7
      env: PLONE_VERSION=5.2.x
      dist: xenial
before_install:
  - mkdir -p buildout-cache/downloads
  - mkdir -p buildout-cache/eggs
install:
  - pip install -r requirements-$PLONE_VERSION.txt
  - buildout -Nc plone-$PLONE_VERSION.cfg annotate
  - buildout -Nc plone-$PLONE_VERSION.cfg
script:
# do code-analysis only on latest plone because there's
# a strange error with configparser in version < 5.1
  - echo $PLONE_VERSION | grep -v 5.2.x || bin/code-analysis
  - bin/test
after_success:
  - bin/coverage.sh
  - pip install coveralls
  - coveralls
after_failure:
  - bin/csslint --version
  - bin/jshint --version
  - bin/jscs --version

